### ISSUE TITLE
Bower components in git tree

### ISSUE THREAD

**Issue by Reshurum** [OakdaleOpenMesh/oakdaleopenmesh-web#51]
At the moment the bower components are committed alongside the rest of the project, the components directory should be ignored though to avoid bloating up repository size.

**Comment by jaccarmac** [comment]
It's important to note that at one point this was necessary for push-to-deploy. Now that push-to-deploy is broken we can indeed ignore the components. However, this makes it more important to keep `bower.json` up-to-date.
